BOARD_TAG = mega2560
ARDUINO_PORT = /dev/cu.usb*

ARDUINO_SKETCHBOOK = .
ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR = ./libraries/Makefile
MONITOR_BAUDRATE = 115200

ARDUINO_LIBS = RGBLedMatrix SPI VirtualWire

include ./libraries/Makefile/arduino-mk/Arduino.mk
