LANG = {
	en : {
		search : 'Search',
		explore : 'Explore',
		playlists : 'Playlists',
		addPlaylist : 'Create playlist',
		savePlaylist : 'Save playlist',
		newPlaylist : 'New playlist',
		title : 'Title',
		category : 'Category',
		topRated : 'Top rated',
		topFavorites : 'Top favorites',
		trending : 'Trending',
		mostShared : 'Most shared',
		uploadSongs : 'Upload songs',
		remove : 'Remove',
		removePlaylist : 'Remove playlist',
		areYouSure : 'Are you sure?',
		addTo : 'Add to',
		addSongs : 'Add songs',
		add : 'Add',
		from: 'from',
		songs : 'songs',
		download : 'Download',
		renameSong : 'Rename Song',
		rename : 'Rename',
		profile : 'Profile',
		lastPlaylists : 'Last playlists',
		subscribe : 'Subscribe',
		subscribed : 'Subscribed',
		subscribedPlaylists : 'Subscribed',
		share : 'Share',
		queue : 'Queue',
		empty : 'Empty',
		addToQueue : 'Add to queue',
		shake : 'Shake',
		allowDups : 'Allow duplicates',
		seeMore : 'See more',
		history : 'History',
		follow : 'Follow',
		following : 'Following',
		categories : [
			'Film',
			'Autos',
			'Music',
			'Animals',
			'Sports',
			'Travel',
			'Games',
			'Videoblog',
			'People',
			'Comedy',
			'Entertainment',
			'News',
			'Howto',
			'Education',
			'Tech',
			'Nonprofit',
			'Movies',
			'Shows',
			'Trailers'
		],
		lang : 'English (US)'
	},
	es : {
		search : 'Buscar',
		explore : 'Explorar',
		playlists : 'Playlists',
		addPlaylist : 'Crear playlist',
		savePlaylist : 'Guardar playlist',
		newPlaylist : 'Nueva playlist',
		title : 'Título',
		category : 'Categoría',
		topRated : 'Top valorados',
		topFavorites : 'Top favoritos',
		trending : 'Trending',
		mostShared : 'Más compartidos',
		uploadSongs : 'Subir canciones',
		remove : 'Eliminar',
		removePlaylist : 'Eliminar playlist',
		areYouSure : '¿Estás seguro?',
		addTo : 'Añadir a',
		addSongs : 'Añadir canciones',
		add : 'Añadir',
		from: 'de',
		songs : 'canciones',
		download : 'Descargar',
		renameSong : 'Cambiar nombre',
		rename : 'Guardar',
		profile : 'Perfil',
		lastPlaylists : 'Últimas playlists',
		subscribe : 'Suscribir',
		subscribed : 'Suscrita',
		subscribedPlaylists : 'Suscritas',
		share : 'Compartir',
		queue : 'Cola',
		empty : 'Vaciar',
		addToQueue : 'Añadir a la cola',
		shake : 'Agitar',
		allowDups : 'Permitir duplicados',
		seeMore : 'Ver más',
		history : 'Historial',
		follow : 'Seguir',
		following : 'Siguiendo',
		categories : [
			'Cine',
			'Motor',
			'Música',
			'Animales',
			'Deportes',
			'Viajes',
			'Juegos',
			'Videoblog',
			'Gente',
			'Comedia',
			'Entretenimiento',
			'Noticias',
			'Howto',
			'Educación',
			'Tecnología',
			'Nonprofit',
			'Películas',
			'Programas',
			'Tráilers'
		],
		lang : 'Castellano (ES)'
	}
};
